### ISSUE TITLE
Adding and removing links to fit the Medium article

### ISSUE THREAD

**Issue by AnneLaure13** [WTTJ/elixir-backend-learning-path#10]
TO BE ADDED

**Functional programming**
[Grokking Simplicity](https://www.manning.com/books/grokking-simplicity) by Eric Normand

**Global learning and tech watch resources**
[Programming Elixir 1.6](https://pragprog.com/titles/elixir16/programming-elixir-1-6/) by Dave Thomas
[Elixir in Action](https://www.manning.com/books/elixir-in-action-second-edition) by Saša Jurić
[Alchemist Camp](https://alchemist.camp/)
[Joy of Elixir](https://joyofelixir.com/toc.html)
[Elixir Newbie](https://www.elixirnewbie.com/blog)
[CodeCast’s Intro to Elixir](https://www.codecast.io/courses/58-intro-to-elixir)
[An Animated Introduction to Elixir](https://markm208.github.io/exbook/)
[ElixirWeekly](https://elixirweekly.net/)
[ElixirStatus](https://elixirstatus.com/)

**Testing your code**
[Testing Elixir](https://pragprog.com/titles/lmelixir/testing-elixir/) by Andrea Leopardi and Jeffrey Matthias
[Property-Based Testing with PropEr, Erlang, and Elixir](https://pragprog.com/titles/fhproper/property-based-testing-with-proper-erlang-and-elixir/) by Fred Hebert

**OTP basics**
[Designing Elixir Systems with OTP](https://pragprog.com/titles/jgotp/designing-elixir-systems-with-otp/) by James Edward Gray, II and Bruce A. Tate

**Phoenix**
[Exploring Elixir and Phoenix: A Comprehensive Overview for Beginners](https://www.fullstack.com/labs/resources/blog/anatomy-of-a-phoenix-app) by FullStack Labs
[Phoenix in Action](https://www.manning.com/books/phoenix-in-action) by Geoffrey Lessel
[Real-Time Phoenix: Build Highly Scalable Systems With Channels](https://www.amazon.fr/Real-time-Phoenix-Scalable-Systems-Channels/dp/1680507192) by Stephen Bussey
[Programming Phoenix 1.4](https://pragprog.com/titles/phoenix14/programming-phoenix-1-4/) by Chris McCord, Bruce Tate, and José Valim
[Programming Phoenix LiveView](https://pragprog.com/titles/liveview/programming-phoenix-liveview/) by Bruce A. Tate and Sophie DeBenedetto

**Ecto**
[Programming Ecto](https://pragprog.com/titles/wmecto/programming-ecto/) by Darin Wilson and Eric Meadows-Jönsson

**Security**
[Elixir Secure Coding Training (ESCT)](https://github.com/podium/elixir-secure-coding)

TO BE REMOVED

**Elixir guide styles**
[An opinionated Elixir Style Guide #2 by Kamil Lelonek](https://blog.lelonek.me/an-opinionated-elixir-style-guide-2-67899790563f) => link is not working

**Phoenix**
[Anatomy of a Phoenix App](https://www.fullstacklabs.co/blog/anatomy-of-a-phoenix-app) => link is not working

TO BE REPLACED

**Basics**
[Basic operators](https://elixir-lang.org/getting-started/basic-operators.html) => link is not the correct one and should be replaced by "https://hexdocs.pm/elixir/1.17.2/operators.html"
[Immutability in Elixir by Dario Ghilardi](https://darioghilardi.com/immutability-in-elixir/) => link is not working and should be replaced by [Understanding Elixir’s Immutability and Data Structures](https://clouddevs.com/elixir/immutability-and-data-structures/) by lago

**Books**
Replace the books section by:
Other resources
For deeper learning about related topics, consider these reads:
- [Metaprogramming Elixir](https://pragprog.com/titles/cmelixir/metaprogramming-elixir/) by Chris McCord
- [Craft GraphQL APIs in Elixir with Absinthe](https://pragprog.com/titles/wwgraphql/craft-graphql-apis-in-elixir-with-absinthe/) by Bruce Williams and Ben Wilson
- [Concurrent Data Processing in Elixir: Fast, Resilient Applications with Otp, Genstage, Flow, and Broadway](https://www.libris.ro/concurrent-data-processing-in-elixir-fast-BRT9781680508192--p25289691.html?srsltid=AfmBOorvrzAOO3AC1ywWleind49cy9UH6UQYWY8lbucA_Fkc8L9BPVQG) by Svilen Gospodinov

**Communities**
[Elixir Community Slack](https://elixir-slackin.herokuapp.com/) => link is not working and should be replaced by "https://elixir-lang.slack.com/join/shared_invite/zt-216sp1w4g-MHgJlFeJKTBCzPejZj7_tw#/shared-invite/email"

**Comment by yannvery** [comment]
Closed with #11
